[package]
name = "overload"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]
bench = false

[dependencies]
ctor = "0.6.0"
shell-words = "1.1.0"

[dev-dependencies]
temp-env = "0.3.6"
